version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-3-223-21-106.compute-1.amazonaws.com
            database: d16j18mjlkvdig
            schema: public
            user: muvmbsrvwgwiab
            password: 0a74f876edbf94725b6f2d070404339474fade30b15dc3645f345b8c3714892b
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true