projects:
  app:
    schemaPath: src/schema/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:3000
  prisma:
    schemaPath: src/generated/schema.graphql
    extensions:
      prisma: prisma/prisma.yml